server:
  port: 8083
  address: 0.0.0.0

spring:
  application:
    name: pet-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://34.66.242.149:5432/pet_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:pet_user}
    password: ${SPRING_DATASOURCE_PASSWORD:leon1611}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  
  # Disable GCS autoconfiguration
  autoconfigure:
    exclude:
      - org.springframework.cloud.gcp.autoconfigure.storage.GcpStorageAutoConfiguration

# Configuración flexible para diferentes redes
ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8000}
    enabled: ${AI_SERVICE_ENABLED:true}

# Configuración GCS flexible
gcs:
  bucket-name: ${GCS_BUCKET_NAME:petnow-dogs-images-app-biometrico-db}
  enabled: ${GCS_ENABLED:true}
  project-id: ${GOOGLE_CLOUD_PROJECT:app-biometrico-db}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always


  expiration: 86400000

logging:
  file:
    name: logs/app.log
  level:
    com.petnow.pet: DEBUG
    org.springframework: DEBUG 