workflows:
  android-workflow:
    name: Android Build - X-NOSE
    environment:
      vars:
        EXPO_PUBLIC_API_URL: "https://xnose-gateway-service-431223568957.us-central1.run.app"
        EXPO_PUBLIC_AI_SERVICE_URL: "https://xnose-ai-service-jrms6vnyga-uc.a.run.app"
        NODE_ENV: "production"
      node: latest
      android_signing:
        - keystore_reference
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
          npm install -g @expo/eas-cli
      - name: Generate keystore
        script: |
          cd frontend
          keytool -genkey -v -keystore android/app/xnose-release-key.keystore -alias xnose-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass xnose2024 -keypass xnose2024 -dname "CN=X-NOSE, OU=Development, O=PetNow, L=City, S=State, C=US"
      - name: Build signed APK
        script: |
          cd frontend
          npx eas build --platform android --profile development --local --non-interactive
    artifacts:
      - frontend/android/app/build/outputs/apk/release/*.apk
      - frontend/android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - leolituma99@gmail.com 