workflows:
  android-workflow:
    name: Android Build
    environment:
      vars:
        EXPO_PUBLIC_API_URL: "https://xnose-gateway-service-431223568957.us-central1.run.app"
        EXPO_PUBLIC_AI_SERVICE_URL: "https://xnose-ai-service-jrms6vnyga-uc.a.run.app"
        NODE_ENV: "production"
        CI: "1"
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Set up Java
        script: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
      - name: Set up Android SDK
        script: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/emulator
          export PATH=$PATH:$ANDROID_HOME/tools
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          export PATH=$PATH:$ANDROID_HOME/platform-tools
      - name: Generate keystore and build AAB
        script: |
          cd frontend/android/app
          keytool -genkey -v -keystore xnose-key.keystore -alias xnose-key -keyalg RSA -keysize 2048 -validity 10000 -storepass xnose123 -keypass xnose123 -dname "CN=XNOSE, OU=Development, O=XNOSE, L=City, S=State, C=US"
          cd ..
          ./gradlew bundleRelease
    artifacts:
      - frontend/android/app/build/outputs/bundle/release/*.aab
      - frontend/android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - leolituma99@gmail.com 