workflows:
  android-workflow:
    name: Android Build
    environment:
      vars:
        EXPO_PUBLIC_API_URL: "https://xnose-gateway-service-431223568957.us-central1.run.app"
        EXPO_PUBLIC_AI_SERVICE_URL: "https://xnose-ai-service-jrms6vnyga-uc.a.run.app"
        NODE_ENV: "production"
        CI: "1"
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Set up Java
        script: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
      - name: Set up Android SDK
        script: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/emulator
          export PATH=$PATH:$ANDROID_HOME/tools
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          export PATH=$PATH:$ANDROID_HOME/platform-tools
      - name: Build APK with Gradle
        script: |
          cd frontend/android
          ./gradlew assembleRelease
    artifacts:
      - frontend/android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - leolituma99@gmail.com 