workflows:
  android-workflow:
    name: Android Build
    environment:
      vars:
        EXPO_PUBLIC_API_URL: "https://xnose-gateway-service-431223568957.us-central1.run.app"
        EXPO_PUBLIC_AI_SERVICE_URL: "https://xnose-ai-service-jrms6vnyga-uc.a.run.app"
        NODE_ENV: "production"
        CI: "1"
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Install EAS CLI
        script: |
          cd frontend
          npm install -g @expo/eas-cli
      - name: Build APK with EAS
        script: |
          cd frontend
          npx eas-cli build --platform android --profile preview --non-interactive
    artifacts:
      - frontend/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - leolituma99@gmail.com 