workflows:
  android-workflow:
    name: Android Build
    environment:
      vars:
        EXPO_PUBLIC_API_URL: "https://xnose-gateway-service-431223568957.us-central1.run.app"
        EXPO_PUBLIC_AI_SERVICE_URL: "https://xnose-ai-service-jrms6vnyga-uc.a.run.app"
        NODE_ENV: "production"
      node: latest
      android_signing:
        - keystore_reference
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build APK
        script: |
          cd frontend
          npx expo build:android --type apk --non-interactive
    artifacts:
      - frontend/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - leolituma99@gmail.com 