services:
  # Gateway Service
  - type: web
    name: xnose-gateway
    runtime: docker
    dockerfilePath: ./gateway-service/Dockerfile
    dockerContext: ./gateway-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: AUTH_SERVICE_URL
        value: https://xnose-auth-service.onrender.com
      - key: OWNER_SERVICE_URL
        value: https://xnose-owner-service.onrender.com
      - key: PET_SERVICE_URL
        value: https://xnose-pet-service.onrender.com
      - key: ALERT_SERVICE_URL
        value: https://xnose-alert-service.onrender.com
      - key: AI_SERVICE_URL
        value: https://xnose-ai-service.onrender.com
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /actuator/health
    autoDeploy: true

  # Auth Service
  - type: web
    name: xnose-auth-service
    runtime: docker
    dockerfilePath: ./auth-service/Dockerfile
    dockerContext: ./auth-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /actuator/health
    autoDeploy: true

  # Owner Service
  - type: web
    name: xnose-owner-service
    runtime: docker
    dockerfilePath: ./owner-service/Dockerfile
    dockerContext: ./owner-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /actuator/health
    autoDeploy: true

  # Pet Service
  - type: web
    name: xnose-pet-service
    runtime: docker
    dockerfilePath: ./pet-service/Dockerfile
    dockerContext: ./pet-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: GCS_BUCKET_NAME
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: AI_SERVICE_URL
        value: https://xnose-ai-service.onrender.com
      - key: AI_SERVICE_ENABLED
        value: "true"
      - key: GCS_ENABLED
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /actuator/health
    autoDeploy: true

  # Alert Service
  - type: web
    name: xnose-alert-service
    runtime: docker
    dockerfilePath: ./alert-service/Dockerfile
    dockerContext: ./alert-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /actuator/health
    autoDeploy: true

  # AI Service
  - type: web
    name: xnose-ai-service
    runtime: docker
    dockerfilePath: ./ai-service/Dockerfile
    dockerContext: ./ai-service
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
      - key: LOG_LEVEL
        value: "INFO"
      - key: SIMILARITY_THRESHOLD
        value: "0.80"
      - key: CONFIDENCE_BOOST
        value: "0.1"
      - key: EMBEDDINGS_FILE
        value: "nose_print_embeddings.json"
      - key: AUDIT_LOG_FILE
        value: "requests.log"
      - key: GCS_BUCKET_NAME
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: CORS_ORIGINS
        value: "https://*.onrender.com,https://*.vercel.app,http://localhost:19000,http://localhost:3000"
    healthCheckPath: /health
    autoDeploy: true

  # Frontend (Static Site)
  - type: web
    name: xnose-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: EXPO_PUBLIC_API_URL
        value: https://xnose-gateway.onrender.com
      - key: EXPO_PUBLIC_AI_SERVICE_URL
        value: https://xnose-ai-service.onrender.com
      - key: EXPO_PUBLIC_GCS_BUCKET_URL
        sync: false
      - key: NODE_ENV
        value: "production"
    healthCheckPath: /
    autoDeploy: true

# Base de datos PostgreSQL
databases:
  - name: xnose-database
    databaseName: xnose_db
    user: xnose_user
    plan: free 