server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      routes:
        # Auth Service
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**
        
        # Owner Service
        - id: owner-service
          uri: ${OWNER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/owners/**
        
        # Pet Service
        - id: pet-service
          uri: ${PET_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/pets/**
        
        # Alert Service
        - id: alert-service
          uri: ${ALERT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/alerts/**
        
        # AI Service
        - id: ai-service
          uri: ${AI_SERVICE_URL:http://localhost:8000}
          predicates:
            - Path=/api/ai/**
      
      # Configuración CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

# Actuator para health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.petnow.gateway: DEBUG 