workflows:
  android-workflow:
    name: Android Build
    environment:
      vars:
        EXPO_PUBLIC_API_URL: "https://xnose-gateway-service-431223568957.us-central1.run.app"
        EXPO_PUBLIC_AI_SERVICE_URL: "https://xnose-ai-service-jrms6vnyga-uc.a.run.app"
      flutter: stable
      xcode: latest
      cocoapods: default
      node: latest
      android_signing:
        - keystore_reference
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx expo install
      - name: Build APK
        script: |
          npx expo build:android --type apk
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - leolituma99@gmail.com 