apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: xnose-ai-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/ai-service:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        - name: SIMILARITY_THRESHOLD
          value: "0.80"
        - name: CONFIDENCE_BOOST
          value: "0.1"
        - name: EMBEDDINGS_FILE
          value: "nose_print_embeddings.json"
        - name: AUDIT_LOG_FILE
          value: "requests.log"
        - name: GCS_ENABLED
          value: "true"
        - name: GCS_BUCKET_NAME
          value: "petnow-dogs-images-PROJECT_ID"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3 