server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: owner-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://34.66.242.149:5432/owner_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:owner_user}
    password: ${SPRING_DATASOURCE_PASSWORD:leon1611}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.petnow.owner: DEBUG 